version: 2
jobs:
  build:
    parallelism: 2
    working_directory: /wp-e2e-tests-jetpack
    docker:
      - image: hoverduck/wp-e2e-tests:0.0.2
        environment:
                NODE_ENV: test
    steps:
      - checkout
      - run: git submodule init && git submodule update --remote --force
      - restore_cache:
          key: << checksum "wp-e2e-tests/package.json" >>
      - run: npm install
      - save_cache:
          paths:
            - wp-e2e-tests/node_modules
          key: << checksum "wp-e2e-tests/package.json" >>
      - store_test_results:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/screenshots/
    bluehost:
      steps:
        - run: ./wp-e2e-tests/run.sh -R -j -H BLUEHOST
    pressable:
      steps:
        - run: ./wp-e2e-tests/run.sh -R -j -H PRESSABLE
    godaddy:
      steps:
        - run: ./wp-e2e-tests/run.sh -R -j -H GODADDY
workflows:
  version: 2
  test_jetpack_hosts:
    jobs:
      - bluehost
      - pressable
      - godaddy
