version: 2
jobs:
  build:
    working_directory: ~/wp-e2e-tests
    docker:
      - image: 'circleci/node:$NODE_VERSION-browsers'
        environment:
          NODE_ENV: test
          TARGET: JETPACK
          JETPACKHOST: PRESSABLE
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-e2e-tests && git checkout origin/${E2E_BRANCH-master}
      - restore_cache:
          keys:
            - v1-npmcache-{{ checksum "wp-e2e-tests/.nvmrc" }}-{{ checksum "wp-e2e-tests/package-lock.json" }}
            - v1-npmcache-{{ checksum "wp-e2e-tests/.nvmrc" }}
            - v1-npmcache
      - run: cd wp-e2e-tests && npm ci
      - save_cache:
          key: v1-npmcache-{{ checksum "wp-e2e-tests/.nvmrc" }}-{{ checksum "wp-e2e-tests/package-lock.json" }}
          paths:
            - "~/.npm"
      - run: sudo chmod +x wp-e2e-tests/node_modules/.bin/magellan
      - run: cd wp-e2e-tests && npm run decryptconfig && ./run.sh -R -j $RUN_ARGS
      - store_test_results:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/screenshots/
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 1,13 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
