defaults: &defaults
  working_directory: /wp-e2e-tests
  docker:
    - image: hoverduck/wp-e2e-tests:0.0.2
      environment:
        NODE_ENV: test
jetpack_host_defaults: &jetpack_host_defaults
  <<: *defaults
  working_directory: /wp-e2e-tests/wp-e2e-tests
  steps:
     - attach_workspace:
         at: /wp-e2e-tests/wp-e2e-tests
     - run: git checkout origin/${E2E_BRANCH-master}
     - run: ./run.sh -R -j
version: 2
jobs:
  configure:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule init && git submodule update --remote --force
      - restore_cache:
          key: << checksum "wp-e2e-tests/package.json" >>
      - run: cd wp-e2e-tests && npm install
      - save_cache:
          paths:
            - wp-e2e-tests/node_modules
          key: << checksum "wp-e2e-tests/package.json" >>
      - persist_to_workspace:
          root: wp-e2e-tests
  bluehost:
    environment:
      JETPACKHOST: BLUEHOST
    <<: *jetpack_host_defaults
  pressable:
    environment:
      JETPACKHOST: PRESSABLE
    <<: *jetpack_host_defaults
  godaddy:
    environment:
      JETPACKHOST: GODADDY
    <<: *jetpack_host_defaults
  gather_artifacts:
    <<: *defaults
    steps:
      - store_test_results:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/screenshots/
workflows:
  version: 2
  test_jetpack_hosts:
    jobs:
      - configure
      - bluehost:
          requires:
            - configure
      - pressable:
          requires:
            - configure
      - godaddy:
          requires:
            - configure
      - gather_artifacts:
          requires:
            - bluehost
            - pressable
            - godaddy
